// Completed-challenge report: stats, CSV/JSON export and the printable window.
function reportValue(v,suffix=""){const n=optionalNumber(v);return n===null?"—":`${n}${suffix}`;}
function challengeReportStats(c){
 const ms=(c.matches||[]).slice().sort((a,b)=>Number(a.no)-Number(b.no)), wins=ms.filter(m=>m.result==="Win").length,losses=ms.filter(m=>m.result==="Loss").length,draws=ms.filter(m=>m.result==="Draw").length;
 const nums=k=>ms.map(m=>optionalNumber(m[k])).filter(v=>v!==null), av=k=>{const a=nums(k);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null};
 const kills=nums("kills").reduce((a,b)=>a+b,0),deaths=nums("deaths").reduce((a,b)=>a+b,0),rr=nums("rrChange");
 return {ms,wins,losses,draws,wr:ms.length?wins/ms.length*100:0,kd:deaths?kills/deaths:(kills||null),acs:av("acs"),adr:av("adr"),dda:av("ddDelta"),kast:av("kast"),hs:av("hs"),netRR:rr.length?rr.reduce((a,b)=>a+b,0):null,finalRank:ms.at(-1)?.rankAfter||c.startRank,finalRR:optionalNumber(ms.at(-1)?.rrAfter)};
}
function downloadText(filename,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0);}
function csvCell(v){const x=v===null||v===undefined?"":String(v);return `"${x.replace(/"/g,'""')}"`;}
window.exportChallengeCSV=function(id){const c=findChallengeById(id);if(!c)return;const fields=["no","agent","map","result","myScore","enemyScore","rankStatus","rankAfter","kills","deaths","assists","acs","adr","ddDelta","hs","kast","rrAfter","rrChange","firstKills","firstDeaths","multiKills","rounds","notes"];const rows=[fields.join(","),...(c.matches||[]).slice().sort((a,b)=>a.no-b.no).map(m=>fields.map(k=>csvCell(m[k])).join(","))];downloadText(`${(c.name||"challenge").replace(/[^a-z0-9_-]+/gi,"-")}-matches.csv`,rows.join("\n"),"text/csv;charset=utf-8");};
window.exportChallengeJSON=function(id){const c=findChallengeById(id);if(!c)return;downloadText(`${(c.name||"challenge").replace(/[^a-z0-9_-]+/gi,"-")}-report.json`,JSON.stringify({exportedAt:new Date().toISOString(),challenge:c,analytics:challengeReportStats(c)},null,2),"application/json");};
window.openChallengeReport=function(id){
 const c=findChallengeById(id);if(!c||!challengeComplete(c))return;const s=challengeReportStats(c),esc=x=>String(x??"").replace(/[&<>\"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[ch]));
 const rows=s.ms.map(m=>`<tr><td>#${m.no}</td><td>${esc(m.result)}</td><td>${esc(m.agent)}</td><td>${esc(m.map)}</td><td>${esc(m.myScore)}–${esc(m.enemyScore)}</td><td>${reportValue(m.kills)}/${reportValue(m.deaths)}/${reportValue(m.assists)}</td><td>${reportValue(m.acs)}</td><td>${reportValue(m.adr)}</td><td>${reportValue(m.ddDelta)}</td><td>${reportValue(m.hs,"%")}</td><td>${reportValue(m.kast,"%")}</td><td>${reportValue(m.rrChange," RR")}</td></tr>`).join("");
 const group=(key)=>Object.entries(s.ms.reduce((o,m)=>{const n=m[key]||"Unknown";o[n]??={n:0,w:0,k:0,d:0};o[n].n++;if(m.result==="Win")o[n].w++;o[n].k+=Number(m.kills)||0;o[n].d+=Number(m.deaths)||0;return o;},{})).sort((a,b)=>b[1].n-a[1].n||a[0].localeCompare(b[0])); const groupRows=key=>group(key).map(([n,v])=>`<tr><td>${esc(n)}</td><td>${v.n}</td><td>${(v.w/v.n*100).toFixed(1)}%</td><td>${v.d?(v.k/v.d).toFixed(2):(v.k||"—")}</td></tr>`).join("");
 const html=`<!doctype html><html><head><title>${esc(c.name)} — Challenge report</title><style>body{font:14px system-ui;margin:32px;color:#16191d}h1{margin-bottom:4px}.muted{color:#68727c}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:24px 0}.k{border:1px solid #d8dde2;border-radius:8px;padding:12px}.k b{display:block;font-size:20px;margin-top:4px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}button{padding:10px 14px;margin-right:8px}@media print{button{display:none}.grid{grid-template-columns:repeat(4,1fr)}body{margin:12mm}}</style></head><body><button onclick="print()">Print / Save as PDF</button><button onclick="opener.exportChallengeCSV('${c.id}')">Export match CSV</button><button onclick="opener.exportChallengeJSON('${c.id}')">Export full JSON</button><h1>${esc(c.name)}</h1><div class="muted">Completed challenge report · ${esc(challengeProgressText(c,{history:true}))} · ${esc(c.startRank)} → ${esc(s.finalRank)}</div><div class="grid"><div class="k">Record<b>${s.wins}W · ${s.losses}L · ${s.draws}D</b></div><div class="k">Win rate<b>${s.wr.toFixed(1)}%</b></div><div class="k">K/D<b>${s.kd===null?"—":s.kd.toFixed(2)}</b></div><div class="k">Net RR<b>${s.netRR===null?"—":`${s.netRR>=0?"+":""}${s.netRR}`}</b></div><div class="k">ACS<b>${s.acs===null?"—":s.acs.toFixed(1)}</b></div><div class="k">ADR<b>${s.adr===null?"—":s.adr.toFixed(1)}</b></div><div class="k">DDΔ<b>${s.dda===null?"—":s.dda.toFixed(1)}</b></div><div class="k">KAST / HS<b>${s.kast===null?"—":s.kast.toFixed(1)+"%"} / ${s.hs===null?"—":s.hs.toFixed(1)+"%"}</b></div></div><h2>Detailed analytics</h2><div class="grid"><div><h3>Agents</h3><table><thead><tr><th>Agent</th><th>Matches</th><th>WR</th><th>K/D</th></tr></thead><tbody>${groupRows("agent")}</tbody></table></div><div><h3>Maps</h3><table><thead><tr><th>Map</th><th>Matches</th><th>WR</th><th>K/D</th></tr></thead><tbody>${groupRows("map")}</tbody></table></div></div><h2>Match history</h2><table><thead><tr><th>Match</th><th>Result</th><th>Agent</th><th>Map</th><th>Score</th><th>K/D/A</th><th>ACS</th><th>ADR</th><th>DDΔ</th><th>HS</th><th>KAST</th><th>RR</th></tr></thead><tbody>${rows}</tbody></table></body></html>`;
 const w=window.open("","_blank");if(!w){showAppNotice("Allow pop-ups to open the printable challenge report.","Report blocked");return;}w.document.write(html);w.document.close();
};
window.showChallengeExportMenu=function(id){openChallengeReport(id);};
